controller_frequency: 10.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

Winter_TrajectoryPlannerROS:
   max_vel_x: 0.6
   min_vel_x: 0.01            
   max_vel_y: 0                # 
   min_vel_y: 0                #
   max_vel_theta: 3.0         # 57.2 degree
   min_vel_theta: -3.0         #
   max_rotational_vel: 3.0
   min_in_place_vel_theta: 0.02 #
   min_in_place_rotational_vel: 0.1
   escape_vel: -0.1            #
   acc_lim_x: 2.8              # 
   acc_lim_y: 0.0              #
   acc_lim_theta: 3.0          #229degree 
   
   yaw_goal_tolerance: 0.10     # 5.72degree
   xy_goal_tolerance: 0.10      #
   path_distance_bias: 0.8      #
   pdist_scale: 0.8
   goal_distance_bias: 0.6
   gdist_scale: 0.6
   occdist_scale: 0.01          #
   
   sim_time: 1.5               #
   sim_granularity: 0.025      #
   angular_sim_granularity: 0.025 #
   vx_samples: 10               #
   vy_samples: 0               #
   vtheta_samples: 20          #
   dwa: true                   #
   simple_attractor: false     #
