<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="winter">
	
        <!-- gazebo -->
        <!--xacro:include filename="$(find winter_description)/urdf/winter.gazebo"/-->
        <xacro:property name="body_radius"      value=".25"/>
        <xacro:property name="body_height"      value=".127"/>

        <xacro:property name="wheel_separation" value="${body_radius*2}"/>
        <xacro:property name="wheel_radius"     value=".075"/>
        <xacro:property name="wheel_length"     value=".06"/>
        <xacro:property name="wheel_color"      value="0 0 .8 1"/>

        <xacro:property name="laser_height"     value=".08"/>
        <xacro:property name="laser_radius"     value=".05"/>

<!--base_link-->
        <link name="base_link">
                <visual>
                        <geometry>
                                <cylinder length="${body_height}" radius="${body_radius}"/>
                        </geometry>
                        <origin xyz="0 0 ${body_height/2+wheel_radius}"/>
                </visual>
                <collision>
                        <geometry>
                                <cylinder length="${body_height}" radius="${body_radius}"/>
                        </geometry>
                        <origin xyz="0 0 ${body_height/2+wheel_radius}"/>
                </collision>
        </link>

<!--laser_link-->
        <link name="laser_link">
                <visual>
                        <geometry>
                                <cylinder length="${laser_height}" radius="${laser_radius}"/>
                        </geometry>
                        <material name="green">
                                <color rgba="0 0.8 0 1"/>
                        </material>
                        <origin xyz="0 0 ${laser_height/2}"/>
                </visual>
                <collision>
                        <geometry>
                                <cylinder length="${laser_height}" radius="${laser_radius}"/>
                        </geometry>
                        <origin xyz="0 0 ${laser_height/2}"/>
                </collision>
        </link>
        <joint name="laser_link_to_base_link" type="fixed">
            <parent link="base_link"/>
            <child link="laser_link"/>
            <origin xyz="0 0 ${body_height+wheel_radius}"/>
        </joint>

<!-- left wheel-->
        <link name="left_wheel">
                <visual>
                        <geometry>
                                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                        </geometry>
                        <material name="blue">
                                <color rgba="${wheel_color}"/>
                        </material>
                        <origin rpy="1.57075 0 0" xyz="0 0 0"/>
                </visual>
        </link>
        <joint name="left_wheel_to_base_link" type="continuous">
                <parent link="base_link"/>
                <child link="left_wheel"/>
                <origin xyz="0.0 ${wheel_separation/2} ${wheel_radius}"/>
                <axis xyz="0 1 0"/>
        </joint>
<!-- right wheel-->
        <link name="right_wheel">
                <visual>
                        <geometry>
                                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                        </geometry>
                        <material name="blue">
                                <color rgba="${wheel_color}"/>
                        </material>
                        <origin rpy="1.57075 0 0" xyz="0 0 0"/>
                </visual>
        </link>
        <joint name="right_wheel_to_base_link" type="continuous">
                <parent link="base_link"/>
                <child link="right_wheel"/>
                <origin xyz="0.0 -${wheel_separation/2} ${wheel_radius}"/>
                <axis xyz="0 1 0"/>
        </joint>

</robot>
